### ISSUE TITLE
CommandException: Unhandled exception executing 'pet enderdragon

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#28] opened 2018-10-16 09:16 UTC
Paper dev 368 (Spigot 1.13.1)
EchoPets compiled as of commit https://github.com/Arnuh/EchoPet/commit/80522c84efb0aa9edbe0405a3d00f7f569aa9362

```
[02:12:36] [Server thread/INFO]: mibby issued server command: /pet enderdragon
[02:12:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet enderdragon' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.1.jar:git-Paper-368]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1743) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1547) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-368]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-368]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Failed to create EntityPet object for mibby
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:90) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-368]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-368]
	... 14 more
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.n(EntityEnderDragonPet.java:182) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityInsentient.<init>(EntityInsentient.java:70) ~[patched_1.13.1.jar:git-Paper-368]
	at net.minecraft.server.v1_13_R2.EntityCreature.<init>(EntityCreature.java:15) ~[patched_1.13.1.jar:git-Paper-368]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityPet.<init>(EntityPet.java:64) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.EntityNoClipPet.<init>(EntityNoClipPet.java:32) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.entity.type.EntityEnderDragonPet.<init>(EntityEnderDragonPet.java:61) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.dsh105.echopet.compat.api.registration.PetRegistrationEntry.createEntityPet(PetRegistrationEntry.java:86) ~[?:?]
	at com.dsh105.echopet.compat.api.entity.PetType.getNewEntityPetInstance(PetType.java:202) ~[?:?]
	at com.dsh105.echopet.compat.nms.v1_13_R2.SpawnUtil.spawn(SpawnUtil.java:54) ~[?:?]
	at com.dsh105.echopet.api.pet.Pet.spawnPet(Pet.java:91) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:442) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:47) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-368]
	... 14 more

```

**Comment by Arnuh** [comment] 2018-10-17 06:01
Duplicate of #24

**Closed as completed by Arnuh** 2018-10-17 06:01 UTC
